using System.Collections.Immutable;
using System.Text;
using LightObjects.Generated.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LightObjects.Generated;

[Generator]
public sealed class GeneratedIdentifierSourceGenerator : IIncrementalGenerator
{
    private const string AttributesNamespace = "LightObjects.Generated";
    private const string GeneratedIdentifierAttributeName = "GeneratedIdentifierAttribute";
    private const string GeneratedIdentifierAttributeFullyQualifiedName = $"{AttributesNamespace}.{GeneratedIdentifierAttributeName}`1";
    private const string GeneratedIdentifierAttributeHint = $"{GeneratedIdentifierAttributeFullyQualifiedName}.g.cs";
    private const string ExcludeFromCodeCoverageAttribute = "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]";

    private static readonly string GeneratedCodeAttribute =
        $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(GeneratedIdentifierSourceGenerator).FullName}", "{typeof(GeneratedIdentifierSourceGenerator).Assembly.GetName().Version}")]""";

    private static readonly DiagnosticDescriptor UnsupportedIdentifierTypeDiagnostic = new("LO0001", "Unsupported identifier type",
        "'{0}' is not a supported identifier type. Only short, int, long, string, or System.Guid are allowed.", "LightObjects.Generated",
        DiagnosticSeverity.Error, true
    );

    private static readonly DiagnosticDescriptor StringIdentifierStructDiagnostic = new("LO0002", "String identifiers must be classes",
        "String identifiers must be declared as classes because default string-backed structs can contain a null value", "LightObjects.Generated",
        DiagnosticSeverity.Warning, true
    );

    private static readonly DiagnosticDescriptor RecordIdentifierDiagnostic = new("LO0003", "Record identifiers are not supported",
        "Record identifiers are not supported. Declare '{0}' as a partial class or struct instead.", "LightObjects.Generated", DiagnosticSeverity.Error, true
    );

    private static readonly DiagnosticDescriptor RefStructIdentifierDiagnostic = new("LO0004", "Ref struct identifiers are not supported",
        "Ref struct identifiers are not supported because generated identifiers implement interfaces and use generic result/converter types",
        "LightObjects.Generated", DiagnosticSeverity.Error, true
    );

    private static readonly DiagnosticDescriptor FileLocalIdentifierDiagnostic = new("LO0005", "File-local identifiers are not supported",
        "File-local identifiers are not supported because generated partial declarations are emitted into a separate file", "LightObjects.Generated",
        DiagnosticSeverity.Error, true
    );

    private static readonly string FileHeader = $"""
                                                 //-----------------------------------------------------------------------------
                                                 // <auto-generated>
                                                 // This code was generated by {nameof(GeneratedIdentifierSourceGenerator)} which
                                                 // can be found in the {typeof(GeneratedIdentifierSourceGenerator).Namespace} namespace.
                                                 //
                                                 // Changes to this file may cause incorrect behavior
                                                 // and will be lost if the code is regenerated.
                                                 // </auto-generated>
                                                 //-----------------------------------------------------------------------------
                                                 #nullable enable
                                                 """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(RegisterAttributes);

        var generatedIdentifiers = context.SyntaxProvider
            .ForAttributeWithMetadataName(GeneratedIdentifierAttributeFullyQualifiedName, Filter, Transform)
            .Collect();

        context.RegisterSourceOutput(generatedIdentifiers, GenerateIdentifier);
    }

    private static void RegisterAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        var source = $"""
                      {FileHeader}

                      namespace {AttributesNamespace};

                      /// <summary>
                      /// Indicates that the LightObjects source generator should generate the implementation
                      /// of a strongly typed identifier for the annotated type.
                      /// </summary>
                      /// <typeparam name="TIdentifier">
                      /// The underlying type to use as the strongly typed identifier.
                      /// </typeparam>
                      {GeneratedCodeAttribute}
                      {ExcludeFromCodeCoverageAttribute}
                      [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                      internal sealed class {GeneratedIdentifierAttributeName}<TIdentifier> : global::System.Attribute;
                      """;
        context.AddSource(GeneratedIdentifierAttributeHint, SourceText.From(source, Encoding.UTF8));
    }

    private static bool Filter(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        return syntaxNode is TypeDeclarationSyntax;
    }

    private static IdentifierResult Transform(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
            return new IdentifierResult();

        if (context.TargetNode is TypeDeclarationSyntax { Modifiers: var modifiers }
            && modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.FileKeyword)))
            return new IdentifierResult { Diagnostic = CreateDiagnostic(FileLocalIdentifierDiagnostic, context, cancellationToken) };

        if (namedTypeSymbol.IsRecord)
            return new IdentifierResult
            {
                Diagnostic = CreateDiagnostic(RecordIdentifierDiagnostic, context, cancellationToken,
                    namedTypeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                ),
            };

        if (namedTypeSymbol.IsRefLikeType)
            return new IdentifierResult { Diagnostic = CreateDiagnostic(RefStructIdentifierDiagnostic, context, cancellationToken) };

        var containingDeclarations = namedTypeSymbol.GetContainingDeclarations(cancellationToken);
        var symbolName = namedTypeSymbol.Name.ToEscapedIdentifier();
        var genericParameters = namedTypeSymbol.GetGenericTypeParameters(cancellationToken);
        var genericParameterConstraints = namedTypeSymbol.GetGenericTypeParameterConstraints(cancellationToken);
        var isStruct = namedTypeSymbol.TypeKind == TypeKind.Struct;
        var accessibility = namedTypeSymbol.DeclaredAccessibility.ToKeyword();

        var attribute = context.Attributes[0].AttributeClass!;
        if (attribute.TypeArguments.Length != 1)
            return new IdentifierResult();

        var typeArgument = attribute.TypeArguments[0];

        string? declaredValueType;
        string? fullValueType;
        var supportsProviderBasedTryParse = false;
        switch (typeArgument.SpecialType)
        {
            case SpecialType.System_Int16:
                declaredValueType = "short";
                fullValueType = "Int16";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_Int32:
                declaredValueType = "int";
                fullValueType = "Int32";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_Int64:
                declaredValueType = "long";
                fullValueType = "Int64";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_String:
                declaredValueType = "string";
                fullValueType = "String";
                if (isStruct)
                {
                    var diagnostic = CreateDiagnostic(StringIdentifierStructDiagnostic, context, cancellationToken);
                    return new IdentifierResult { Diagnostic = diagnostic };
                }
                break;
            default:
                if (typeArgument is not { Name: "Guid", ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true } })
                {
                    var diagnostic = CreateDiagnostic(UnsupportedIdentifierTypeDiagnostic, context, cancellationToken,
                        typeArgument.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                    );
                    return new IdentifierResult { Diagnostic = diagnostic };
                }

                declaredValueType = "Guid";
                fullValueType = "Guid";
                break;
        }

        var symbol = new Identifier
        {
            ContainingDeclarations = containingDeclarations,
            Name = symbolName,
            GenericParameters = genericParameters,
            GenericParameterConstraints = genericParameterConstraints,
            IsStruct = isStruct,
            Accessibility = accessibility,
            DeclaredValueType = declaredValueType,
            FullValueType = fullValueType,
            SupportsProviderBasedTryParse = supportsProviderBasedTryParse,
            HasCustomValidation = HasCustomValidationMethod(namedTypeSymbol, typeArgument,
                context.SemanticModel.Compilation.GetTypeByMetadataName("LightResults.Result")
            ),
        };

        return new IdentifierResult { Value = symbol };
    }

    private static Diagnostic CreateDiagnostic(
        DiagnosticDescriptor descriptor,
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken,
        params object[] messageArgs
    )
    {
        var attributeSyntax = context.Attributes[0]
            .ApplicationSyntaxReference
            ?.GetSyntax(cancellationToken);
        var location = attributeSyntax?.GetLocation() ?? context.TargetNode.GetLocation();
        return Diagnostic.Create(descriptor, location, messageArgs);
    }

    private static bool HasCustomValidationMethod(INamedTypeSymbol namedTypeSymbol, ITypeSymbol valueType, INamedTypeSymbol? resultType)
    {
        if (resultType is null)
            return false;

        foreach (var member in namedTypeSymbol.GetMembers("Validate"))
        {
            if (member is not IMethodSymbol method)
                continue;

            if (method is
                {
                    MethodKind: MethodKind.Ordinary,
                    DeclaredAccessibility: Accessibility.Private,
                    IsStatic: true,
                    Arity: 0,
                    Parameters: [{ RefKind: RefKind.None }],
                }
                && SymbolEqualityComparer.Default.Equals(method.ReturnType, resultType)
                && SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, valueType))
                return true;
        }

        return false;
    }

    private static void GenerateIdentifier(SourceProductionContext context, ImmutableArray<IdentifierResult> generatedIdentifiers)
    {
        foreach (var result in generatedIdentifiers)
        {
            if (result.Diagnostic is { } diagnostic)
                context.ReportDiagnostic(diagnostic);

            var symbol = result.Value;
            if (!symbol.HasValue)
                continue;

            var identifier = symbol.Value;

            var symbolNamespace = identifier.ContainingDeclarations.ToNamespace();
            var symbolName = identifier.Name;
            var genericParameters = identifier.GenericParameters;
            var genericParameterConstraints = identifier.GenericParameterConstraints;
            var genericParameterList = genericParameters.ToGenericParameterList();
            var genericParameterConstraintList = genericParameterConstraints.ToIndentedGenericConstraintList();
            var unboundGenericParameterList = genericParameters.ToUnboundGenericParameterList();
            var symbolReferenceName = $"{symbolName}{genericParameterList}";
            var symbolXmlDocReferenceName = $"{symbolName}{genericParameters.ToXmlDocGenericParameterList()}";
            var converterName = $"{symbolName}TypeConverter{genericParameterList}";
            var jsonConverterName = $"{symbolName}JsonConverter{genericParameterList}";
            var converterTypeOfName = $"{symbolName}TypeConverter{unboundGenericParameterList}";
            var jsonConverterTypeOfName = $"{symbolName}JsonConverter{unboundGenericParameterList}";
            var hasGenericContext = HasGenericContext(identifier);
            var genericContextHelperName = ToGenericContextHelperName(identifier);
            var typeDescriptionProviderName = $"{genericContextHelperName}TypeDescriptionProvider";
            var jsonConverterFactoryName = $"{genericContextHelperName}JsonConverterFactory";
            var typeDescriptionProviderTypeOfName = ToFullyQualifiedTypeReference(symbolNamespace, typeDescriptionProviderName);
            var jsonConverterFactoryTypeOfName = ToFullyQualifiedTypeReference(symbolNamespace, jsonConverterFactoryName);
            var unboundIdentifierTypeReference = ToFullyQualifiedUnboundTypeReference(identifier);
            var isStruct = identifier.IsStruct;
            var accessibility = identifier.Accessibility;
            var declaredValueType = identifier.DeclaredValueType;
            var valueTypeReference = declaredValueType switch
            {
                "Guid" => "global::System.Guid",
                "string" => "global::System.String",
                _ => declaredValueType,
            };
            var fullValueType = identifier.FullValueType;

            var supportsProviderBasedTryParse = identifier.SupportsProviderBasedTryParse;
            var hasCustomValidation = identifier.HasCustomValidation;

            var source = new StringBuilder();

            source.AppendLine($"""
                               //-----------------------------------------------------------------------------
                               // <auto-generated>
                               // This code was generated by {nameof(GeneratedIdentifierSourceGenerator)} which
                               // can be found in the {typeof(GeneratedIdentifierSourceGenerator).Namespace} namespace.
                               //
                               // Changes to this file may cause incorrect behavior
                               // and will be lost if the code is regenerated.
                               // </auto-generated>
                               //-----------------------------------------------------------------------------

                               #nullable enable

                               """
            );

            if (symbolNamespace.Length > 0)
                source.AppendLine($"""
                                   namespace {symbolNamespace};

                                   """
                );

            var containingTypeCount = 0;
            foreach (var declaration in identifier.ContainingDeclarations)
            {
                if (declaration.Type == DeclarationType.Namespace)
                    continue;

                source.AppendLine(declaration.ToPartialDeclaration());
                source.AppendLine("{");
                source.AppendLine();
                containingTypeCount++;
            }

            source.AppendLine(GeneratedCodeAttribute);

            if (hasGenericContext)
            {
                if (!isStruct)
                    source.AppendLine($$"""
                                        [global::System.ComponentModel.TypeDescriptionProvider(typeof({{typeDescriptionProviderTypeOfName}}))]
                                        """
                    );

                source.AppendLine($$"""
                                    [global::System.Text.Json.Serialization.JsonConverter(typeof({{jsonConverterFactoryTypeOfName}}))]
                                    """
                );
            }
            else
            {
                source.AppendLine($$"""
                                    [global::System.ComponentModel.TypeConverter(typeof({{converterTypeOfName}}))]
                                    [global::System.Text.Json.Serialization.JsonConverter(typeof({{jsonConverterTypeOfName}}))]
                                    """
                );
            }

            source.AppendLine($$"""
                                {{accessibility}} {{(isStruct ? "readonly" : "sealed")}} partial {{(isStruct ? "struct" : "class")}} {{symbolReferenceName}} :
                                    global::LightObjects.ICreatableValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>,
                                """
            );

            if (declaredValueType != "string")
                source.AppendLine($$"""
                                        global::LightObjects.IParsableValueObject<{{symbolReferenceName}}>,
                                    """
                );

            source.AppendLine($$"""
                                    global::LightObjects.IValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>,
                                    global::System.IComparable<{{symbolReferenceName}}>,
                                    global::System.IComparable{{genericParameterConstraintList}}
                                {
                                """
            );

            source.AppendLine($"""
                                   {valueTypeReference} global::LightObjects.IValueObject<{valueTypeReference}, {symbolReferenceName}>.Value => _value;

                                   private readonly {valueTypeReference} _value;

                               """
            );

            source.AppendLine($$"""
                                    private {{symbolName}}({{valueTypeReference}} value, bool skipValidation = false)
                                    {
                                        if (!skipValidation)
                                            global::LightObjects.ValueObjectException.ThrowIfFailed(Validate(value));

                                        _value = value;
                                    }

                                """
            );

            source.AppendLine($$"""
                                    /// <summary>Creates a <see cref="{{symbolXmlDocReferenceName}}" /> from the specified value.</summary>
                                    /// <param name="value">The underlying value.</param>
                                    /// <returns>A <see cref="{{symbolXmlDocReferenceName}}" /> that wraps <paramref name="value" />.</returns>
                                    public static {{symbolReferenceName}} Create({{valueTypeReference}} value)
                                    {
                                        var result = TryCreate(value);
                                        if (result.IsSuccess(out var identifier, out var error))
                                            return identifier;

                                        throw new global::LightObjects.ValueObjectException(error.Message);
                                    }

                                """
            );

            source.AppendLine($$"""
                                    /// <summary>Attempts to create a <see cref="{{symbolXmlDocReferenceName}}" /> from the specified value.</summary>
                                    /// <param name="value">The underlying value.</param>
                                    /// <returns>A result containing the created <see cref="{{symbolXmlDocReferenceName}}" />, or an error when <paramref name="value" /> is not valid.</returns>
                                    public static global::LightResults.Result<{{symbolReferenceName}}> TryCreate({{valueTypeReference}} value)
                                    {
                                        var validation = Validate(value);
                                        if (validation.IsFailure(out var error))
                                            return global::LightResults.Result.Failure<{{symbolReferenceName}}>(error);

                                        var identifier = new {{symbolReferenceName}}(value, true);
                                        return global::LightResults.Result.Success<{{symbolReferenceName}}>(identifier);
                                    }

                                """
            );

            if (declaredValueType != "string")
            {
                source.AppendLine($$"""
                                        /// <summary>Parses the specified string into a <see cref="{{symbolXmlDocReferenceName}}" />.</summary>
                                        /// <param name="s">The string to parse.</param>
                                        /// <returns>A <see cref="{{symbolXmlDocReferenceName}}" /> parsed from <paramref name="s" />.</returns>
                                        public static {{symbolReferenceName}} Parse(global::System.String s)
                                        {
                                            var result = TryParse(s);
                                            if (result.IsSuccess(out var identifier, out var error))
                                                return identifier;

                                            throw new global::LightObjects.ValueObjectException(error.Message);
                                        }

                                    """
                );

                source.AppendLine($$"""
                                        /// <summary>Attempts to parse the specified string into a <see cref="{{symbolXmlDocReferenceName}}" />.</summary>
                                        /// <param name="s">The string to parse.</param>
                                        /// <returns>A result containing the parsed <see cref="{{symbolXmlDocReferenceName}}" />, or an error when <paramref name="s" /> is not valid.</returns>
                                        public static global::LightResults.Result<{{symbolReferenceName}}> TryParse(global::System.String s)
                                        {
                                            if ({{valueTypeReference}}.TryParse(s, out var value))
                                                return TryCreate(value);

                                            return global::LightResults.Result.Failure<{{symbolReferenceName}}>("The string is not a valid identifier.");
                                        }

                                    """
                );

                source.AppendLine($$"""
                                        /// <summary>Attempts to parse the specified string into a <see cref="{{symbolXmlDocReferenceName}}" />.</summary>
                                        /// <param name="s">The string to parse.</param>
                                        /// <param name="identifier">When this method returns, contains the parsed identifier if parsing succeeded; otherwise, the default value.</param>
                                        /// <returns><c>true</c> if <paramref name="s" /> was parsed successfully; otherwise, <c>false</c>.</returns>
                                        public static bool TryParse(global::System.String s, out {{symbolReferenceName}} identifier)
                                        {
                                            if ({{valueTypeReference}}.TryParse(s, out var value))
                                                return TryCreate(value).IsSuccess(out identifier);

                                            identifier = default;
                                            return false;
                                        }

                                    """
                );

                if (supportsProviderBasedTryParse)
                    source.AppendLine($$"""
                                            /// <summary>Attempts to parse the specified string into a <see cref="{{symbolXmlDocReferenceName}}" /> using the specified format provider.</summary>
                                            /// <param name="s">The string to parse.</param>
                                            /// <param name="provider">The format provider to use when parsing <paramref name="s" />.</param>
                                            /// <param name="identifier">When this method returns, contains the parsed identifier if parsing succeeded; otherwise, the default value.</param>
                                            /// <returns><c>true</c> if <paramref name="s" /> was parsed successfully; otherwise, <c>false</c>.</returns>
                                            public static bool TryParse(global::System.String s, global::System.IFormatProvider provider, out {{symbolReferenceName}} identifier)
                                            {
                                                if ({{valueTypeReference}}.TryParse(s, provider, out var value))
                                                    return TryCreate(value).IsSuccess(out identifier);

                                                identifier = default;
                                                return false;
                                            }

                                        """
                    );
            }

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public bool Equals({{symbolReferenceName}} other)
                                        {
                                            return {{(declaredValueType is "string" ?
                                                "global::System.String.Equals(_value, other._value, global::System.StringComparison.Ordinal)" :
                                                "_value.Equals(other._value)")}};
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                      /// <inheritdoc />
                                      public bool Equals({{symbolReferenceName}}? other)
                                      {
                                          if (other is null)
                                              return false;
                                          if (global::System.Object.ReferenceEquals(this, other))
                                              return true;
                                          return {{(declaredValueType is "string" ?
                                              "global::System.String.Equals(_value, other._value, global::System.StringComparison.Ordinal)" :
                                              "_value.Equals(other._value)")}};
                                      }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public override bool Equals(global::System.Object? obj)
                                        {
                                            return obj is {{symbolReferenceName}} other && Equals(other);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public override bool Equals(global::System.Object? obj)
                                        {
                                            if (obj is null)
                                                return false;
                                            if (global::System.Object.ReferenceEquals(this, obj))
                                                return true;
                                            return obj is {{symbolReferenceName}} other && Equals(other);
                                        }

                                    """
                );

            if (declaredValueType is "long" or "Guid" or "string")
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public override int GetHashCode()
                                        {
                                            return {{(declaredValueType is "string" ?
                                                "global::System.StringComparer.Ordinal.GetHashCode(_value)" :
                                                "_value.GetHashCode()")}};
                                        }

                                    """
                );
            else
                source.AppendLine("""
                                      /// <inheritdoc />
                                      public override int GetHashCode()
                                      {
                                          return _value;
                                      }

                                  """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether two <see cref="{{symbolXmlDocReferenceName}}" /> values are equal.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator ==({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.Equals(right);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether two <see cref="{{symbolXmlDocReferenceName}}" /> values are equal.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if the values are equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator ==({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null && right is null)
                                                return true;
                                            if (left is null || right is null)
                                                return false;
                                            if (global::System.Object.ReferenceEquals(left, right))
                                                return true;
                                            return left.Equals(right);
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether two <see cref="{{symbolXmlDocReferenceName}}" /> values are not equal.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator !=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return !left.Equals(right);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether two <see cref="{{symbolXmlDocReferenceName}}" /> values are not equal.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if the values are not equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator !=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null && right is null)
                                                return false;
                                            if (left is null || right is null)
                                                return true;
                                            if (global::System.Object.ReferenceEquals(left, right))
                                                return false;
                                            return !left.Equals(right);
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Compares this <see cref="{{symbolXmlDocReferenceName}}" /> value with another value of the same type.</summary>
                                        /// <param name="other">The other value to compare.</param>
                                        /// <returns>A signed integer that is less than zero if this value is less than <paramref name="other" />, zero if the values are equal, or greater than zero if this value is greater than <paramref name="other" />.</returns>
                                        public int CompareTo({{symbolReferenceName}} other)
                                        {
                                            return _value.CompareTo(other._value);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Compares this <see cref="{{symbolXmlDocReferenceName}}" /> value with another value of the same type.</summary>
                                        /// <param name="other">The other value to compare, or <c>null</c>.</param>
                                        /// <returns>A signed integer that is less than zero if this value is less than <paramref name="other" />, zero if the values are equal, or greater than zero if this value is greater than <paramref name="other" />. A non-null value compares greater than <c>null</c>.</returns>
                                        public int CompareTo({{symbolReferenceName}}? other)
                                        {
                                            if (other is null)
                                                return 1;
                                            if (global::System.Object.ReferenceEquals(this, other))
                                                return 0;
                                            return {{(declaredValueType is "string" ?
                                                "global::System.String.Compare(_value, other._value, global::System.StringComparison.Ordinal)" :
                                                "_value.CompareTo(other._value)")}};
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Compares this <see cref="{{symbolXmlDocReferenceName}}" /> value with another object.</summary>
                                        /// <param name="obj">The object to compare, or <c>null</c>.</param>
                                        /// <returns>A signed integer that is less than zero if this value is less than <paramref name="obj" />, zero if the values are equal, or greater than zero if this value is greater than <paramref name="obj" />. A non-null value compares greater than <c>null</c>.</returns>
                                        /// <exception cref="System.ArgumentException"><paramref name="obj" /> is not <c>null</c> and is not a <see cref="{{symbolXmlDocReferenceName}}" />.</exception>
                                        public int CompareTo(global::System.Object? obj)
                                        {
                                            if (global::System.Object.ReferenceEquals(null, obj))
                                                return 1;
                                            return obj is {{symbolReferenceName}} other ? CompareTo(other) : throw new global::System.ArgumentException($"Object must be of type {nameof({{symbolReferenceName}})}.");
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Compares this <see cref="{{symbolXmlDocReferenceName}}" /> value with another object.</summary>
                                        /// <param name="obj">The object to compare, or <c>null</c>.</param>
                                        /// <returns>A signed integer that is less than zero if this value is less than <paramref name="obj" />, zero if the values are equal, or greater than zero if this value is greater than <paramref name="obj" />. A non-null value compares greater than <c>null</c>.</returns>
                                        /// <exception cref="System.ArgumentException"><paramref name="obj" /> is not <c>null</c> and is not a <see cref="{{symbolXmlDocReferenceName}}" />.</exception>
                                        public int CompareTo(global::System.Object? obj)
                                        {
                                            if (obj is null)
                                                return 1;
                                            if (global::System.Object.ReferenceEquals(this, obj))
                                                return 0;
                                            return obj is {{symbolReferenceName}} other ? CompareTo(other) : throw new global::System.ArgumentException($"Object must be of type {nameof({{symbolReferenceName}})}.");
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is less than the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator <({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) < 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is less than the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator <({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return (right is null ? 0 : -1) < 0;
                                            return left.CompareTo(right) < 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is greater than the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator >({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) > 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is greater than the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator >({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return false;
                                            return left.CompareTo(right) > 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is less than or equal to the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator <=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) <= 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is less than or equal to the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator <=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return true;
                                            return left.CompareTo(right) <= 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is greater than or equal to the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator >=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) >= 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the left <see cref="{{symbolXmlDocReferenceName}}" /> value is greater than or equal to the right value.</summary>
                                        /// <param name="left">The left value to compare.</param>
                                        /// <param name="right">The right value to compare.</param>
                                        /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                                        public static bool operator >=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return (right is null ? 0 : -1) >= 0;
                                            return left.CompareTo(right) >= 0;
                                        }

                                    """
                );

            if (declaredValueType != "string")
                source.AppendLine($$"""
                                        /// <summary>Returns the underlying value of the <see cref="{{symbolXmlDocReferenceName}}" />.</summary>
                                        /// <returns>The underlying value.</returns>
                                        public {{valueTypeReference}} To{{fullValueType}}()
                                        {
                                            return _value;
                                        }

                                    """
                );

            if (declaredValueType == "Guid")
                source.AppendLine("""
                                      /// <summary>Returns the string representation of the underlying value.</summary>
                                      /// <returns>The string representation of the underlying value.</returns>
                                      public override global::System.String ToString()
                                      {
                                          return _value.ToString();
                                      }

                                  """
                );
            else if (declaredValueType == "string")
                source.AppendLine("""
                                      /// <summary>Returns the underlying string value.</summary>
                                      /// <returns>The underlying string value.</returns>
                                      public override global::System.String ToString()
                                      {
                                          return _value;
                                      }

                                  """
                );
            else
                source.AppendLine("""
                                      /// <summary>Returns the invariant-culture string representation of the underlying value.</summary>
                                      /// <returns>The invariant-culture string representation of the underlying value.</returns>
                                      public override global::System.String ToString()
                                      {
                                          return _value.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                                      }

                                  """
                );

            if (!hasCustomValidation)
            {
                if (declaredValueType == "string")
                    source.AppendLine($$"""
                                            private static global::LightResults.Result Validate({{valueTypeReference}} value)
                                            {
                                                if (global::System.String.IsNullOrWhiteSpace(value))
                                                    return global::LightResults.Result.Failure("The value must not be empty.");

                                                return global::LightResults.Result.Success();
                                            }
                                        """
                    );
                else
                    source.AppendLine($$"""
                                            private static global::LightResults.Result Validate({{valueTypeReference}} value)
                                            {
                                                return global::LightResults.Result.Success();
                                            }
                                        """
                    );
            }

            source.AppendLine("""
                              }

                              """
            );

            if (!hasGenericContext)
            {
                source.AppendLine($$"""
                                    /// <summary>Provides type conversion for <see cref="{{symbolXmlDocReferenceName}}" /> values.</summary>
                                    {{GeneratedCodeAttribute}}
                                    {{ExcludeFromCodeCoverageAttribute}}
                                    {{accessibility}} sealed class {{converterName}} : global::System.ComponentModel.TypeConverter{{genericParameterConstraintList}}
                                    {
                                        /// <inheritdoc />
                                        public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)
                                        {
                                            return sourceType == typeof(global::System.String)
                                                || sourceType == typeof({{valueTypeReference}})
                                                || base.CanConvertFrom(context, sourceType);
                                        }

                                        /// <inheritdoc />
                                        public override global::System.Object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, global::System.Object value)
                                        {
                                            if (value is {{valueTypeReference}} identifierValue)
                                                return {{symbolReferenceName}}.Create(identifierValue);

                                            if (value is global::System.String stringValue)
                                                return {{(declaredValueType == "string" ? $"{symbolReferenceName}.Create(stringValue)" : $"{symbolReferenceName}.Parse(stringValue)")}};

                                            return base.ConvertFrom(context, culture, value);
                                        }
                                    }

                                    """
                );
                source.AppendLine($$"""
                                    /// <summary>Provides JSON conversion for <see cref="{{symbolXmlDocReferenceName}}" /> values.</summary>
                                    {{GeneratedCodeAttribute}}
                                    {{ExcludeFromCodeCoverageAttribute}}
                                    {{accessibility}} sealed class {{jsonConverterName}} : global::System.Text.Json.Serialization.JsonConverter<{{symbolReferenceName}}>{{genericParameterConstraintList}}
                                    {
                                        /// <inheritdoc />
                                        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {{symbolReferenceName}} identifier, global::System.Text.Json.JsonSerializerOptions options)
                                        {
                                            var value = ((global::LightObjects.IValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>)identifier).Value;
                                    """
                );

                if (declaredValueType == "Guid")
                    source.AppendLine("""        writer.WriteStringValue(value.ToString());""");
                else if (declaredValueType == "string")
                    source.AppendLine("""        writer.WriteStringValue(value);""");
                else
                    source.AppendLine("""        writer.WriteNumberValue(value);""");

                source.AppendLine($$"""
                                        }

                                        /// <inheritdoc />
                                        public override {{symbolReferenceName}} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                                        {
                                            var value = reader.Get{{fullValueType}}();
                                    """
                );
                if (declaredValueType == "string" && !hasCustomValidation)
                    source.AppendLine("""
                                              if (global::System.String.IsNullOrWhiteSpace(value))
                                                  throw new global::System.InvalidOperationException("The value must not be empty.");

                                      """
                    );
                var jsonValueExpression = declaredValueType == "string" && hasCustomValidation ? "value!" : "value";
                source.Append($$"""
                                        return {{symbolReferenceName}}.Create({{jsonValueExpression}});
                                    }
                                }

                                """
                );
            }

            for (var index = 0; index < containingTypeCount; index++)
            {
                source.AppendLine("""
                                  }

                                  """
                );
            }

            if (hasGenericContext)
            {
                if (!isStruct)
                    AppendGenericContextTypeDescriptionProvider(source, typeDescriptionProviderName, valueTypeReference, declaredValueType);

                AppendGenericContextJsonConverterFactory(source, jsonConverterFactoryName, unboundIdentifierTypeReference, valueTypeReference, fullValueType,
                    declaredValueType, hasCustomValidation
                );
            }

            var hintPrefix = identifier.ContainingDeclarations.ToFullyQualifiedName();
            var targetHintName = $"{identifier.Name.ToGeneratedIdentifierPart()}{identifier.GenericParameters.ToGenericAritySuffix()}";
            var hint = hintPrefix.Length == 0 ? $"{targetHintName}.g.cs" : $"{hintPrefix}.{targetHintName}.g.cs";
            context.AddSource(hint, source.ToString());
        }
    }

    private static bool HasGenericContext(Identifier identifier)
    {
        if (identifier.GenericParameters.Count > 0)
            return true;

        foreach (var declaration in identifier.ContainingDeclarations)
        {
            if (declaration.Type != DeclarationType.Namespace && declaration.GenericParameters.Count > 0)
                return true;
        }

        return false;
    }

    private static string ToFullyQualifiedTypeReference(string symbolNamespace, string typeName)
    {
        return symbolNamespace.Length == 0 ? $"global::{typeName}" : $"global::{symbolNamespace}.{typeName}";
    }

    private static string ToGenericContextHelperName(Identifier identifier)
    {
        var builder = new StringBuilder("LightObjectsGenerated");

        foreach (var declaration in identifier.ContainingDeclarations)
        {
            if (declaration.Type == DeclarationType.Namespace)
                continue;

            builder.Append('_');
            builder.Append(declaration.Name.ToGeneratedIdentifierPart());
            builder.Append(declaration.GenericParameters.Count);
        }

        builder.Append('_');
        builder.Append(identifier.Name.ToGeneratedIdentifierPart());
        builder.Append(identifier.GenericParameters.Count);

        return builder.ToString();
    }

    private static string ToFullyQualifiedUnboundTypeReference(Identifier identifier)
    {
        var builder = new StringBuilder("global::");
        var needsSeparator = false;

        foreach (var declaration in identifier.ContainingDeclarations)
        {
            if (needsSeparator)
                builder.Append('.');

            builder.Append(declaration.Name);

            if (declaration.Type != DeclarationType.Namespace)
                builder.Append(declaration.GenericParameters.ToUnboundGenericParameterList());

            needsSeparator = true;
        }

        if (needsSeparator)
            builder.Append('.');

        builder.Append(identifier.Name);
        builder.Append(identifier.GenericParameters.ToUnboundGenericParameterList());

        return builder.ToString();
    }

    private static void AppendGenericContextTypeDescriptionProvider(
        StringBuilder source,
        string typeDescriptionProviderName,
        string valueTypeReference,
        string declaredValueType
    )
    {
        source.AppendLine($$"""
                            {{GeneratedCodeAttribute}}
                            {{ExcludeFromCodeCoverageAttribute}}
                            internal sealed class {{typeDescriptionProviderName}} : global::System.ComponentModel.TypeDescriptionProvider
                            {
                                private static readonly global::System.ComponentModel.TypeDescriptionProvider DefaultProvider =
                                    global::System.ComponentModel.TypeDescriptor.GetProvider(typeof(global::System.Object));

                                /// <summary>Initializes a new instance of the <see cref="{{typeDescriptionProviderName}}" /> class.</summary>
                                public {{typeDescriptionProviderName}}()
                                    : base(DefaultProvider)
                                {
                                }

                                /// <inheritdoc />
                                public override global::System.ComponentModel.ICustomTypeDescriptor GetTypeDescriptor(global::System.Type objectType, global::System.Object? instance)
                                {
                                    var descriptor = base.GetTypeDescriptor(objectType, instance);
                                    return new IdentifierTypeDescriptor(descriptor, objectType);
                                }

                                {{GeneratedCodeAttribute}}
                                {{ExcludeFromCodeCoverageAttribute}}
                                private sealed class IdentifierTypeDescriptor : global::System.ComponentModel.CustomTypeDescriptor
                                {
                                    private readonly global::System.Type _objectType;

                                    /// <summary>Initializes a new instance of the <see cref="IdentifierTypeDescriptor" /> class.</summary>
                                    /// <param name="parent">The parent type descriptor.</param>
                                    /// <param name="objectType">The identifier type described by this descriptor.</param>
                                    public IdentifierTypeDescriptor(global::System.ComponentModel.ICustomTypeDescriptor? parent, global::System.Type objectType)
                                        : base(parent)
                                    {
                                        _objectType = objectType;
                                    }

                                    /// <inheritdoc />
                                    public override global::System.ComponentModel.TypeConverter GetConverter()
                                    {
                                        return new IdentifierTypeConverter(_objectType);
                                    }
                                }

                                /// <summary>Provides type conversion for generated identifier values.</summary>
                                {{GeneratedCodeAttribute}}
                                {{ExcludeFromCodeCoverageAttribute}}
                                private sealed class IdentifierTypeConverter : global::System.ComponentModel.TypeConverter
                                {
                                    private readonly global::System.Reflection.MethodInfo _createMethod;
                            """
        );

        if (declaredValueType != "string")
            source.AppendLine("""
                                      private readonly global::System.Reflection.MethodInfo _parseMethod;
                              """
            );

        source.AppendLine($$"""

                                    /// <summary>Initializes a new instance of the <see cref="IdentifierTypeConverter" /> class.</summary>
                                    /// <param name="identifierType">The identifier type converted by this converter.</param>
                                    public IdentifierTypeConverter(global::System.Type identifierType)
                                    {
                                        _createMethod = identifierType.GetMethod(
                                            "Create",
                                            global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static,
                                            binder: null,
                                            types: new[] { typeof({{valueTypeReference}}) },
                                            modifiers: null
                                        ) ?? throw new global::System.InvalidOperationException("The generated identifier Create method could not be found.");
                            """
        );

        if (declaredValueType != "string")
            source.AppendLine("""

                                      _parseMethod = identifierType.GetMethod(
                                          "Parse",
                                          global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static,
                                          binder: null,
                                          types: new[] { typeof(global::System.String) },
                                          modifiers: null
                                      ) ?? throw new global::System.InvalidOperationException("The generated identifier Parse method could not be found.");
                              """
            );

        source.AppendLine($$"""
                                    }

                                    /// <inheritdoc />
                                    public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)
                                    {
                                        return sourceType == typeof(global::System.String)
                                            || sourceType == typeof({{valueTypeReference}})
                                            || base.CanConvertFrom(context, sourceType);
                                    }

                                    /// <inheritdoc />
                                    public override global::System.Object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, global::System.Object value)
                                    {
                                        if (value is {{valueTypeReference}} identifierValue)
                                            return Create(identifierValue);

                                        if (value is global::System.String stringValue)
                                            return {{(declaredValueType == "string" ? "Create(stringValue)" : "Parse(stringValue)")}};

                                        return base.ConvertFrom(context, culture, value);
                                    }

                                    private global::System.Object Create({{valueTypeReference}} value)
                                    {
                                        return Invoke(_createMethod, value);
                                    }
                            """
        );

        if (declaredValueType != "string")
            source.AppendLine("""

                                  private global::System.Object Parse(global::System.String value)
                                  {
                                      return Invoke(_parseMethod, value);
                                  }
                              """
            );

        source.AppendLine("""

                                  private static global::System.Object Invoke(global::System.Reflection.MethodInfo method, global::System.Object? value)
                                  {
                                      try
                                      {
                                          return method.Invoke(null, new[] { value })!;
                                      }
                                      catch (global::System.Reflection.TargetInvocationException exception) when (exception.InnerException is not null)
                                      {
                                          global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
                                          throw;
                                      }
                                  }
                              }
                          }

                          """
        );
    }

    private static void AppendGenericContextJsonConverterFactory(
        StringBuilder source,
        string jsonConverterFactoryName,
        string unboundIdentifierTypeReference,
        string valueTypeReference,
        string fullValueType,
        string declaredValueType,
        bool hasCustomValidation
    )
    {
        source.AppendLine($$"""
                            /// <summary>Provides JSON converters for generated identifier values.</summary>
                            {{GeneratedCodeAttribute}}
                            {{ExcludeFromCodeCoverageAttribute}}
                            internal sealed class {{jsonConverterFactoryName}} : global::System.Text.Json.Serialization.JsonConverterFactory
                            {
                                /// <inheritdoc />
                                public override bool CanConvert(global::System.Type typeToConvert)
                                {
                                    return typeToConvert.IsGenericType
                                        && typeToConvert.GetGenericTypeDefinition() == typeof({{unboundIdentifierTypeReference}});
                                }

                                /// <inheritdoc />
                                public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                                {
                                    var converterType = typeof(IdentifierJsonConverter<>).MakeGenericType(typeToConvert);
                                    return (global::System.Text.Json.Serialization.JsonConverter)global::System.Activator.CreateInstance(converterType)!;
                                }

                                /// <summary>Provides JSON conversion for <typeparamref name="TIdentifier" /> values.</summary>
                                /// <typeparam name="TIdentifier">The identifier type to convert.</typeparam>
                                {{GeneratedCodeAttribute}}
                                {{ExcludeFromCodeCoverageAttribute}}
                                private sealed class IdentifierJsonConverter<TIdentifier> : global::System.Text.Json.Serialization.JsonConverter<TIdentifier>
                                    where TIdentifier : notnull
                                {
                                    private static readonly global::System.Reflection.MethodInfo CreateMethod =
                                        typeof(TIdentifier).GetMethod(
                                            "Create",
                                            global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Static,
                                            binder: null,
                                            types: new[] { typeof({{valueTypeReference}}) },
                                            modifiers: null
                                        ) ?? throw new global::System.InvalidOperationException("The generated identifier Create method could not be found.");

                                    /// <inheritdoc />
                                    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, TIdentifier identifier, global::System.Text.Json.JsonSerializerOptions options)
                                    {
                                        var value = ((global::LightObjects.IValueObject<{{valueTypeReference}}, TIdentifier>)identifier).Value;
                            """
        );

        if (declaredValueType == "Guid")
            source.AppendLine("""            writer.WriteStringValue(value.ToString());""");
        else if (declaredValueType == "string")
            source.AppendLine("""            writer.WriteStringValue(value);""");
        else
            source.AppendLine("""            writer.WriteNumberValue(value);""");

        source.AppendLine($$"""
                                    }

                                    /// <inheritdoc />
                                    public override TIdentifier Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                                    {
                                        var value = reader.Get{{fullValueType}}();
                            """
        );

        if (declaredValueType == "string" && !hasCustomValidation)
            source.AppendLine("""
                                      if (global::System.String.IsNullOrWhiteSpace(value))
                                          throw new global::System.InvalidOperationException("The value must not be empty.");

                              """
            );

        var jsonValueExpression = declaredValueType == "string" && hasCustomValidation ? "value!" : "value";
        source.AppendLine($$"""
                                        return Create({{jsonValueExpression}});
                                    }

                                    private static TIdentifier Create({{valueTypeReference}} value)
                                    {
                                        try
                                        {
                                            return (TIdentifier)CreateMethod.Invoke(null, new global::System.Object?[] { value })!;
                                        }
                                        catch (global::System.Reflection.TargetInvocationException exception) when (exception.InnerException is not null)
                                        {
                                            global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
                                            throw;
                                        }
                                    }
                                }
                            }

                            """
        );
    }

    private readonly record struct IdentifierResult
    {
        public Identifier? Value { get; init; }
        public Diagnostic? Diagnostic { get; init; }
    }

    private readonly record struct Identifier
    {
        public required EquatableImmutableArray<Declaration> ContainingDeclarations { get; init; }
        public required string Name { get; init; }
        public required EquatableImmutableArray<string> GenericParameters { get; init; }
        public required EquatableImmutableArray<string> GenericParameterConstraints { get; init; }
        public required bool IsStruct { get; init; }
        public required string Accessibility { get; init; }
        public required string DeclaredValueType { get; init; }
        public required string FullValueType { get; init; }
        public required bool SupportsProviderBasedTryParse { get; init; }
        public required bool HasCustomValidation { get; init; }
    }
}
