using System.Collections.Immutable;
using System.Text;
using LightObjects.Generated.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace LightObjects.Generated;

[Generator]
public sealed class GeneratedIdentifierSourceGenerator : IIncrementalGenerator
{
    private const string AttributesNamespace = "LightObjects.Generated";
    private const string GeneratedIdentifierAttributeName = "GeneratedIdentifierAttribute";
    private const string GeneratedIdentifierAttributeFullyQualifiedName = $"{AttributesNamespace}.{GeneratedIdentifierAttributeName}`1";
    private const string GeneratedIdentifierAttributeHint = $"{GeneratedIdentifierAttributeFullyQualifiedName}.g.cs";

    private static readonly DiagnosticDescriptor UnsupportedIdentifierTypeDiagnostic = new(
        id: "LO0001",
        title: "Unsupported identifier type",
        messageFormat: "'{0}' is not a supported identifier type. Only short, int, long, string, or System.Guid are allowed.",
        category: "LightObjects.Generated",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    private static readonly DiagnosticDescriptor StringIdentifierStructDiagnostic = new(
        id: "LO0002",
        title: "String identifiers must be classes",
        messageFormat: "String identifiers must be declared as classes because default string-backed structs can contain a null value",
        category: "LightObjects.Generated",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );

    private static readonly string FileHeader = $"""
                                                 //-----------------------------------------------------------------------------
                                                 // <auto-generated>
                                                 // This code was generated by {nameof(GeneratedIdentifierSourceGenerator)} which
                                                 // can be found in the {typeof(GeneratedIdentifierSourceGenerator).Namespace} namespace.
                                                 //
                                                 // Changes to this file may cause incorrect behavior
                                                 // and will be lost if the code is regenerated.
                                                 // </auto-generated>
                                                 //-----------------------------------------------------------------------------
                                                 #nullable enable
                                                 """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(RegisterAttributes);

        var generatedIdentifiers = context.SyntaxProvider
            .ForAttributeWithMetadataName(GeneratedIdentifierAttributeFullyQualifiedName, Filter, Transform)
            .Collect();

        context.RegisterSourceOutput(generatedIdentifiers, GenerateIdentifier);
    }

    private static void RegisterAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        var source = $"""
                      {FileHeader}

                      namespace {AttributesNamespace};

                      /// <summary>
                      /// Indicates that the LightObjects source generator should generate the implementation
                      /// of a strongly typed identifier for the annotated type.
                      /// </summary>
                      /// <typeparam name="TIdentifier">
                      /// The underlying type to use as the strongly typed identifier.
                      /// </typeparam>
                      [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                      internal sealed class {GeneratedIdentifierAttributeName}<TIdentifier> : global::System.Attribute;
                      """;
        context.AddSource(GeneratedIdentifierAttributeHint, SourceText.From(source, Encoding.UTF8));
    }

    private static bool Filter(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        return syntaxNode.IsKind(SyntaxKind.StructDeclaration) || syntaxNode.IsKind(SyntaxKind.ClassDeclaration);
    }

    private static IdentifierResult Transform(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
            return new IdentifierResult();

        var containingDeclarations = namedTypeSymbol.GetContainingDeclarations(cancellationToken);
        var symbolName = namedTypeSymbol.Name;
        var genericParameters = namedTypeSymbol.GetGenericTypeParameters(cancellationToken);
        var genericParameterConstraints = namedTypeSymbol.GetGenericTypeParameterConstraints(cancellationToken);
        var isStruct = namedTypeSymbol.TypeKind == TypeKind.Struct;
        var accessibility = namedTypeSymbol.DeclaredAccessibility.ToKeyword();

        var attribute = context.Attributes[0].AttributeClass!;
        if (attribute.TypeArguments.Length != 1)
            return new IdentifierResult();

        var typeArgument = attribute.TypeArguments[0];

        string? declaredValueType;
        string? fullValueType;
        var supportsProviderBasedTryParse = false;
        switch (typeArgument.SpecialType)
        {
            case SpecialType.System_Int16:
                declaredValueType = "short";
                fullValueType = "Int16";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_Int32:
                declaredValueType = "int";
                fullValueType = "Int32";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_Int64:
                declaredValueType = "long";
                fullValueType = "Int64";
                supportsProviderBasedTryParse = true;
                break;
            case SpecialType.System_String:
                declaredValueType = "string";
                fullValueType = "String";
                if (isStruct)
                {
                    var attributeSyntax = context.Attributes[0].ApplicationSyntaxReference?.GetSyntax(cancellationToken);
                    var location = attributeSyntax?.GetLocation() ?? context.TargetNode.GetLocation();
                    var diagnostic = Diagnostic.Create(StringIdentifierStructDiagnostic, location);
                    return new IdentifierResult { Diagnostic = diagnostic };
                }
                break;
            default:
                if (typeArgument is not { Name: "Guid", ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true } })
                {
                    var attributeSyntax = context.Attributes[0].ApplicationSyntaxReference?.GetSyntax(cancellationToken);
                    var location = attributeSyntax?.GetLocation() ?? context.TargetNode.GetLocation();
                    var diagnostic = Diagnostic.Create(
                        UnsupportedIdentifierTypeDiagnostic,
                        location,
                        typeArgument.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                    );
                    return new IdentifierResult { Diagnostic = diagnostic };
                }

                declaredValueType = "Guid";
                fullValueType = "Guid";
                break;
        }

        var symbol = new Identifier
        {
            ContainingDeclarations = containingDeclarations,
            Name = symbolName,
            GenericParameters = genericParameters,
            GenericParameterConstraints = genericParameterConstraints,
            IsStruct = isStruct,
            Accessibility = accessibility,
            DeclaredValueType = declaredValueType,
            FullValueType = fullValueType,
            SupportsProviderBasedTryParse = supportsProviderBasedTryParse,
            HasCustomValidation = HasCustomValidationMethod(
                namedTypeSymbol,
                typeArgument,
                context.SemanticModel.Compilation.GetTypeByMetadataName("LightResults.Result")
            )
        };

        return new IdentifierResult { Value = symbol };
    }

    private static bool HasCustomValidationMethod(INamedTypeSymbol namedTypeSymbol, ITypeSymbol valueType, INamedTypeSymbol? resultType)
    {
        if (resultType is null)
            return false;

        foreach (var member in namedTypeSymbol.GetMembers("Validate"))
        {
            if (member is not IMethodSymbol method)
                continue;

            if (method is
                {
                    MethodKind: MethodKind.Ordinary,
                    DeclaredAccessibility: Accessibility.Private,
                    IsStatic: true,
                    Arity: 0,
                    Parameters: [{ RefKind: RefKind.None }]
                }
                && SymbolEqualityComparer.Default.Equals(method.ReturnType, resultType)
                && SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, valueType))
            {
                return true;
            }
        }

        return false;
    }

    private static void GenerateIdentifier(SourceProductionContext context, ImmutableArray<IdentifierResult> generatedIdentifiers)
    {
        foreach (var result in generatedIdentifiers)
        {
            if (result.Diagnostic is { } diagnostic)
                context.ReportDiagnostic(diagnostic);

            var symbol = result.Value;
            if (!symbol.HasValue)
                continue;

            var identifier = symbol.Value;

            var symbolNamespace = identifier.ContainingDeclarations.ToNamespace();
            var symbolName = identifier.Name;
            var genericParameters = identifier.GenericParameters;
            var genericParameterConstraints = identifier.GenericParameterConstraints;
            var genericParameterList = genericParameters.ToGenericParameterList();
            var genericParameterConstraintList = genericParameterConstraints.ToIndentedGenericConstraintList();
            var unboundGenericParameterList = genericParameters.ToUnboundGenericParameterList();
            var symbolReferenceName = $"{symbolName}{genericParameterList}";
            var converterName = $"{symbolName}TypeConverter{genericParameterList}";
            var jsonConverterName = $"{symbolName}JsonConverter{genericParameterList}";
            var converterTypeOfName = $"{symbolName}TypeConverter{unboundGenericParameterList}";
            var jsonConverterTypeOfName = $"{symbolName}JsonConverter{unboundGenericParameterList}";
            var isStruct = identifier.IsStruct;
            var accessibility = identifier.Accessibility;
            var declaredValueType = identifier.DeclaredValueType;
            var valueTypeReference = declaredValueType switch
            {
                "Guid" => "global::System.Guid",
                "string" => "global::System.String",
                _ => declaredValueType,
            };
            var fullValueType = identifier.FullValueType;

            var supportsProviderBasedTryParse = identifier.SupportsProviderBasedTryParse;
            var hasCustomValidation = identifier.HasCustomValidation;

            var source = new StringBuilder();

            source.AppendLine($"""
                               //-----------------------------------------------------------------------------
                               // <auto-generated>
                               // This code was generated by {nameof(GeneratedIdentifierSourceGenerator)} which
                               // can be found in the {typeof(GeneratedIdentifierSourceGenerator).Namespace} namespace.
                               //
                               // Changes to this file may cause incorrect behavior
                               // and will be lost if the code is regenerated.
                               // </auto-generated>
                               //-----------------------------------------------------------------------------

                               #nullable enable

                               """
            );

            if (symbolNamespace.Length > 0)
                source.AppendLine($"""
                                   namespace {symbolNamespace};

                                   """
                );

            var containingTypeCount = 0;
            foreach (var declaration in identifier.ContainingDeclarations)
            {
                if (declaration.Type == DeclarationType.Namespace)
                    continue;

                source.AppendLine(declaration.ToPartialDeclaration());
                source.AppendLine("{");
                source.AppendLine();
                containingTypeCount++;
            }

            source.AppendLine($$"""
                                [global::System.ComponentModel.TypeConverter(typeof({{converterTypeOfName}}))]
                                [global::System.Text.Json.Serialization.JsonConverter(typeof({{jsonConverterTypeOfName}}))]
                                {{accessibility}} {{(isStruct ? "readonly" : "sealed")}} partial {{(isStruct ? "struct" : "class")}} {{symbolReferenceName}} :
                                    global::LightObjects.ICreatableValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>,
                                """
            );

            if (declaredValueType != "string")
                source.AppendLine($$"""
                                        global::LightObjects.IParsableValueObject<{{symbolReferenceName}}>,
                                    """
                );

            source.AppendLine($$"""
                                    global::LightObjects.IValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>,
                                    global::System.IComparable<{{symbolReferenceName}}>,
                                    global::System.IComparable{{genericParameterConstraintList}}
                                {
                                """
            );

            source.AppendLine($"""
                                   {valueTypeReference} global::LightObjects.IValueObject<{valueTypeReference}, {symbolReferenceName}>.Value => _value;
                               
                                   private readonly {valueTypeReference} _value;

                               """
            );

            source.AppendLine($$"""
                                    private {{symbolName}}({{valueTypeReference}} value, bool skipValidation = false)
                                    {
                                        if (!skipValidation)
                                            global::LightObjects.ValueObjectException.ThrowIfFailed(Validate(value));
                                
                                        _value = value;
                                    }

                                """
            );

            source.AppendLine($$"""
                                    /// <inheritdoc />
                                    public static {{symbolReferenceName}} Create({{valueTypeReference}} value)
                                    {
                                        var result = TryCreate(value);
                                        if (result.IsSuccess(out var identifier, out var error))
                                            return identifier;
                                
                                        throw new global::LightObjects.ValueObjectException(error.Message);
                                    }

                                """
            );

            source.AppendLine($$"""
                                    /// <inheritdoc />
                                    public static global::LightResults.Result<{{symbolReferenceName}}> TryCreate({{valueTypeReference}} value)
                                    {
                                        var validation = Validate(value);
                                        if (validation.IsFailure(out var error))
                                            return global::LightResults.Result.Failure<{{symbolReferenceName}}>(error);
                                
                                        var identifier = new {{symbolReferenceName}}(value, true);
                                        return global::LightResults.Result.Success<{{symbolReferenceName}}>(identifier);
                                    }

                                """
            );

            if (declaredValueType != "string")
            {
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public static {{symbolReferenceName}} Parse(global::System.String s)
                                        {
                                            var result = TryParse(s);
                                            if (result.IsSuccess(out var identifier, out var error))
                                                return identifier;
                                    
                                            throw new global::LightObjects.ValueObjectException(error.Message);
                                        }

                                    """
                );

                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public static global::LightResults.Result<{{symbolReferenceName}}> TryParse(global::System.String s)
                                        {
                                            if ({{valueTypeReference}}.TryParse(s, out var value))
                                                return TryCreate(value);
                                    
                                            return global::LightResults.Result.Failure<{{symbolReferenceName}}>("The string is not a valid identifier.");
                                        }

                                    """
                );

                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public static bool TryParse(global::System.String s, out {{symbolReferenceName}} identifier)
                                        {
                                            if ({{valueTypeReference}}.TryParse(s, out var value))
                                                return TryCreate(value).IsSuccess(out identifier);
                                    
                                            identifier = default;
                                            return false;
                                        }

                                    """
                );

                if (supportsProviderBasedTryParse)
                {
                    source.AppendLine($$"""
                                            /// <inheritdoc />
                                            public static bool TryParse(global::System.String s, global::System.IFormatProvider provider, out {{symbolReferenceName}} identifier)
                                            {
                                                if ({{valueTypeReference}}.TryParse(s, provider, out var value))
                                                    return TryCreate(value).IsSuccess(out identifier);

                                                identifier = default;
                                                return false;
                                            }

                                        """
                    );
                }
            }

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public bool Equals({{symbolReferenceName}} other)
                                        {
                                            return {{(declaredValueType is "string" ?
                                                "global::System.String.Equals(_value, other._value, global::System.StringComparison.Ordinal)" :
                                                "_value.Equals(other._value)")}};
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                      /// <inheritdoc />
                                      public bool Equals({{symbolReferenceName}}? other)
                                      {
                                          if (other is null)
                                              return false;
                                          if (global::System.Object.ReferenceEquals(this, other))
                                              return true;
                                          return {{(declaredValueType is "string" ?
                                              "global::System.String.Equals(_value, other._value, global::System.StringComparison.Ordinal)" :
                                              "_value.Equals(other._value)")}};
                                      }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public override bool Equals(global::System.Object? obj)
                                        {
                                            return obj is {{symbolReferenceName}} other && Equals(other);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public override bool Equals(global::System.Object? obj)
                                        {
                                            if (obj is null)
                                                return false;
                                            if (global::System.Object.ReferenceEquals(this, obj))
                                                return true;
                                            return obj is {{symbolReferenceName}} other && Equals(other);
                                        }

                                    """
                );

            if (declaredValueType is "long" or "Guid" or "string")
                source.AppendLine($$"""
                                      /// <inheritdoc />
                                      public override int GetHashCode()
                                      {
                                          return {{(declaredValueType is "string" ?
                                                  "global::System.StringComparer.Ordinal.GetHashCode(_value)" :
                                                  "_value.GetHashCode()")}};
                                      }

                                  """
                );
            else
                source.AppendLine("""
                                      /// <inheritdoc />
                                      public override int GetHashCode()
                                      {
                                          return _value;
                                      }

                                  """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether two instances of <see cref="{{symbolName}}" /> are equal.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the instances are equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator ==({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.Equals(right);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether two instances of <see cref="{{symbolName}}" /> are equal.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the instances are equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator ==({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null && right is null)
                                                return true;
                                            if (left is null || right is null)
                                                return false;
                                            if (global::System.Object.ReferenceEquals(left, right))
                                                return true;
                                            return left.Equals(right);
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether two instances of <see cref="{{symbolName}}" /> are not equal.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the instances are not equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator !=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return !left.Equals(right);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether two instances of <see cref="{{symbolName}}" /> are not equal.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the instances are not equal; otherwise, <c>false</c>.</returns>
                                        public static bool operator !=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null && right is null)
                                                return false;
                                            if (left is null || right is null)
                                                return true;
                                            if (global::System.Object.ReferenceEquals(left, right))
                                                return false;
                                            return !left.Equals(right);
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public int CompareTo({{symbolReferenceName}} other)
                                        {
                                            return _value.CompareTo(other._value);
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public int CompareTo({{symbolReferenceName}}? other)
                                        {
                                            if (other is null)
                                                return 1;
                                            if (global::System.Object.ReferenceEquals(this, other))
                                                return 0;
                                            return {{(declaredValueType is "string" ?
                                                "global::System.String.Compare(_value, other._value, global::System.StringComparison.Ordinal)" :
                                                "_value.CompareTo(other._value)")}};
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public int CompareTo(global::System.Object? obj)
                                        {
                                            if (global::System.Object.ReferenceEquals(null, obj))
                                                return 1;
                                            return obj is {{symbolReferenceName}} other ? CompareTo(other) : throw new global::System.ArgumentException($"Object must be of type {nameof({{symbolReferenceName}})}.");
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <inheritdoc />
                                        public int CompareTo(global::System.Object? obj)
                                        {
                                            if (obj is null)
                                                return 1;
                                            if (global::System.Object.ReferenceEquals(this, obj))
                                                return 0;
                                            return obj is {{symbolReferenceName}} other ? CompareTo(other) : throw new global::System.ArgumentException($"Object must be of type {nameof({{symbolReferenceName}})}.");
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is less than the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is less than the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator <({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) < 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is less than the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is less than the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator <({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return (right is null ? 0 : -1) < 0;
                                            return left.CompareTo(right) < 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is greater than the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is greater than the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator >({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) > 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is greater than the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is greater than the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator >({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return false;
                                            return left.CompareTo(right) > 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is less than or equal to the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is less than or equal to the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator <=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) <= 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is less than or equal to the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is less than or equal to the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator <=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return true;
                                            return left.CompareTo(right) <= 0;
                                        }

                                    """
                );

            if (isStruct)
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is greater than or equal to the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is greater than or equal to the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator >=({{symbolReferenceName}} left, {{symbolReferenceName}} right)
                                        {
                                            return left.CompareTo(right) >= 0;
                                        }

                                    """
                );
            else
                source.AppendLine($$"""
                                        /// <summary>Determines whether the first instance of <see cref="{{symbolName}}" /> is greater than or equal to the second instance.</summary>
                                        /// <param name="left">The first instance to compare.</param>
                                        /// <param name="right">The second instance to compare.</param>
                                        /// <returns><c>true</c> if the first instance is greater than or equal to the second instance; otherwise, <c>false</c>.</returns>
                                        public static bool operator >=({{symbolReferenceName}}? left, {{symbolReferenceName}}? right)
                                        {
                                            if (left is null)
                                                return (right is null ? 0 : -1) >= 0;
                                            return left.CompareTo(right) >= 0;
                                        }

                                    """
                );

            if (declaredValueType != "string")
                source.AppendLine($$"""
                                        /// <summary>Gets the underlying value of the <see cref="{{symbolName}}" />.</summary>
                                        /// <returns>The underlying value of the <see cref="{{symbolName}}" />.</returns>
                                        public {{valueTypeReference}} To{{fullValueType}}()
                                        {
                                            return _value;
                                        }

                                    """
                );

            if (declaredValueType == "Guid")
                source.AppendLine("""
                                      /// <inheritdoc />
                                      public override global::System.String ToString()
                                      {
                                          return _value.ToString();
                                      }

                                  """
                );
            else if (declaredValueType == "string")
                source.AppendLine("""
                                      /// <inheritdoc />
                                      public override global::System.String ToString()
                                      {
                                          return _value;
                                      }

                                  """
                );
            else
                source.AppendLine("""
                                      /// <inheritdoc />
                                      public override global::System.String ToString()
                                      {
                                          return _value.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                                      }

                                  """
                );

            if (!hasCustomValidation)
            {
                if (declaredValueType == "string")
                    source.AppendLine($$"""
                                            private static global::LightResults.Result Validate({{valueTypeReference}} value)
                                            {
                                                if (global::System.String.IsNullOrWhiteSpace(value))
                                                    return global::LightResults.Result.Failure("The value must not be empty.");
                                        
                                                return global::LightResults.Result.Success();
                                            }
                                        """
                    );
                else
                    source.AppendLine($$"""
                                            private static global::LightResults.Result Validate({{valueTypeReference}} value)
                                            {
                                                return global::LightResults.Result.Success();
                                            }
                                        """
                    );
            }

            source.AppendLine("""
                              }

                              """
            );

            source.AppendLine($$"""
                                {{accessibility}} sealed class {{converterName}} : global::System.ComponentModel.TypeConverter{{genericParameterConstraintList}}
                                {
                                    public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType)
                                    {
                                        return sourceType == typeof(global::System.String)
                                            || sourceType == typeof({{valueTypeReference}})
                                            || base.CanConvertFrom(context, sourceType);
                                    }

                                    public override global::System.Object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, global::System.Object value)
                                    {
                                        if (value is {{valueTypeReference}} identifierValue)
                                            return {{symbolReferenceName}}.Create(identifierValue);

                                        if (value is global::System.String stringValue)
                                            return {{(declaredValueType == "string" ? $"{symbolReferenceName}.Create(stringValue)" : $"{symbolReferenceName}.Parse(stringValue)")}};

                                        return base.ConvertFrom(context, culture, value);
                                    }
                                }

                                """
            );
            source.AppendLine($$"""
                                {{accessibility}} sealed class {{jsonConverterName}} : global::System.Text.Json.Serialization.JsonConverter<{{symbolReferenceName}}>{{genericParameterConstraintList}}
                                {
                                    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {{symbolReferenceName}} identifier, global::System.Text.Json.JsonSerializerOptions options)
                                    {
                                        var value = ((global::LightObjects.IValueObject<{{valueTypeReference}}, {{symbolReferenceName}}>)identifier).Value;
                                """
            );

            if (declaredValueType == "Guid")
                source.AppendLine("""        writer.WriteStringValue(value.ToString());""");
            else if (declaredValueType == "string")
                source.AppendLine("""        writer.WriteStringValue(value);""");
            else
                source.AppendLine("""        writer.WriteNumberValue(value);""");

            source.AppendLine($$"""
                                    }
                                
                                    public override {{symbolReferenceName}} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                                    {
                                        var value = reader.Get{{fullValueType}}();
                                """
            );
            if (declaredValueType == "string" && !hasCustomValidation)
                source.AppendLine("""
                                          if (global::System.String.IsNullOrWhiteSpace(value))
                                              throw new global::System.InvalidOperationException("The value must not be empty.");

                                  """
                );
            var jsonValueExpression = declaredValueType == "string" && hasCustomValidation ? "value!" : "value";
            source.Append($$"""
                                    return {{symbolReferenceName}}.Create({{jsonValueExpression}});
                                }
                            }

                            """
            );

            for (var index = 0; index < containingTypeCount; index++)
            {
                source.AppendLine("""
                                  }

                                  """
                );
            }

            var hintPrefix = identifier.ContainingDeclarations.ToFullyQualifiedName();
            var targetHintName = $"{identifier.Name}{identifier.GenericParameters.ToGenericAritySuffix()}";
            var hint = hintPrefix.Length == 0 ? $"{targetHintName}.g.cs" : $"{hintPrefix}.{targetHintName}.g.cs";
            context.AddSource(hint, source.ToString());
        }
    }

    private readonly record struct IdentifierResult
    {
        public Identifier? Value { get; init; }
        public Diagnostic? Diagnostic { get; init; }
    }

    private readonly record struct Identifier
    {
        public required EquatableImmutableArray<Declaration> ContainingDeclarations { get; init; }
        public required string Name { get; init; }
        public required EquatableImmutableArray<string> GenericParameters { get; init; }
        public required EquatableImmutableArray<string> GenericParameterConstraints { get; init; }
        public required bool IsStruct { get; init; }
        public required string Accessibility { get; init; }
        public required string DeclaredValueType { get; init; }
        public required string FullValueType { get; init; }
        public required bool SupportsProviderBasedTryParse { get; init; }
        public required bool HasCustomValidation { get; init; }
    }
}
